### ISSUE TITLE
no compiled DocumentSnapshot/QuerySnapshot access available.

### ISSUE THREAD

**Issue by giladv** [mikkopaderes/mock-cloud-firestore#58]
hello,

in the real sdk the following are available:
firebase.firestore.DocumentSnapshot
firebase.firestore.QuerySnapshot
firebase.firestore.QueryDocumentSnapshot

i cannot seem to be able to access similarly the mock versions.

**Comment by rmmmp** [comment]
Those are available. How're you trying to use the library?

**Comment by giladv** [comment]
which still doesn't work, probably jest is making a different copy when parsing it
`firebase.firestore().collection('users').doc('123').get().then(user => console.log(user instanceof DocumentSnapshot)) // false`
