### ISSUE TITLE
Deprecation in favor of official solution

### ISSUE THREAD

**Issue by mikkopaderes** [mikkopaderes/mock-cloud-firestore#62]
I initially created this project as a temporary solution until the Firebase team releases a way to run tests locally. They did that recently and we now have a way to run a local emulator of Cloud Firestore.

I haven't used it yet as I haven't touched Cloud Firestore in a while. If it fits the needs of the majority, I'd be happy to deprecate this project as it just isn't practical to play catch up with them.

Check it out [here](https://firebase.google.com/docs/firestore/security/test-rules-emulator).

**Comment by mesqueeb** [comment]
@rmmmp Don't give up! We're almost there!!!

**Comment by rmmmp** [comment]
@mesqueeb thanks but I'm really looking to deprecate this as we already have an official solution. I'll probably try to port one project of mine and see how it goes.

**Comment by iluuu1994** [comment]
I've unsuccessfully tried getting the official solution to work for like 2 hours. This project works very well and doesn't require some service running in the background. I wouldn't deprecate this until the official solution works well. 🙂

**Comment by mesqueeb** [comment]
Ditto

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikkopaderes** [comment]
@oliver-foggin I haven't tried it yet but I did presume the tests to take a while to finish because of the network requests. Out of curiosity, did you get it to work in a browser environment or a nodejs one?

**Comment by oliver-foggin** [comment]
OK... after more testing I found that it wasn't the emulator taking the time... it was `nock`.

Creating a stubbed endpoint is taking 200ms per endpoint. Removed that now and the emulator is back up and running really quickly.

**Comment by mikkopaderes** [comment]
Keeping the project open for now because the test emulator is only available in the Node.js SDK
