### ISSUE TITLE
[Issue] orderBy doesn't work

### ISSUE THREAD

**Issue by fjcaetano** [mikkopaderes/mock-cloud-firestore#72]
Hello, first of all, thank you for this repo. It is really helpful and does simplify a lot for testing firebase.

I'm not being able to make `orderBy` work in my tests. The tested method goes a bit like this:
```js
const result = await this.collection.orderBy('score', 'desc').limit(1).get();
```

And in my tests I have:
```js
jest.mock(
  'react-native-firebase',
  () =>
    new MockFirebase(
      stubFirebase({
        some_collection: [
          { score: 0, content: 'foo' },
          { score: 1, content: 'bar' },
          { score: 2, content: 'xpto' },
        ],
      }),
    ),
);
```

`stubFirebase` is a method I created to simplify creating mock data structure for tests. I have already checked and the issue is not here because it works for other cases.

Finally, this is my test:
```js
it('loads the item with highest score', async () => {
  const dataSource = new DataSource();

  const result = await dataSource.loadItem();

  expect(result).toEqual(mockItems[2]);
});
```

I expected `result` to equal `{ score: 2, content: 'xpto' }` which is the item with highest score, however, it always returns `{ score: 0, content: 'foo' }`.

Is this intentional? Am I doing something wrong? I'm more than happy to work on a PR, if you could point me to where to start.

**Comment by mikkopaderes** [comment]
Can you try first on passing in a plain fixture data rather than the `stubFirebase`. This is just so we can truly rule it out as the problem.

Also please share the fixture data if it still didn't work.

**Comment by fjcaetano** [comment]
Same result. This is the data used:
```
    new MockFirebase({
      __collection__: {
        some_collection: {
          __doc__: {
            '0': { score: 0, content: 'foo' },
            '1': { score: 1, content: 'bar' },
            '2': { score: 2, content: 'xpto' },
          },
        },
      },
    })
```

It's always returning the item with the lowest id, regardless of the order of the items sent in the mock data. I tried changing the first item's id to 3, and it returned the item with id 1: `{ score: 1, content: 'bar' }`.

Perhaps the sorting is not being applied to the field sent to `orderBy`, but by id?

**Comment by mikkopaderes** [comment]
I've replicated the issue and it seems to be happening for docs which has numbers `0` or `'0'` as IDs. I'll look to fix this.

**Comment by mikkopaderes** [comment]
To explain the issues more, this is because JS sorts the object keys when they represent numbers.

e.g.

```javascript
console.log({ 2: 'foo', 1: 'bar' });
```

Would display

```javascript
{ 1: 'bar', 2: 'foo' }
```

**Comment by fjcaetano** [comment]
@mikkopaderes indeed, if I add non-number string id to my mock data it does solve the issue, and it is something I can do on my end. I've changed my data helper method to prepend a underscore to the ids, and the issue goes away. Thanks.

Indeed, it's really weird that JS sorts the keys when they're numeric. Is there any way to prevent this?

**Comment by mikkopaderes** [comment]
@fjcaetano not that I know of. I can try experimenting with a different data type but it would require some trivial refactoring.

I'll hold off with that changes for now until then. This issue can be reopened at another time if necessary.
