### ISSUE TITLE
Using set() with merge enabled, nested objects are not merged

### ISSUE THREAD

**Issue by kimroen** [mikkopaderes/mock-cloud-firestore#73]
If you update a nested property document reference using `set` with `merge: true`, the entire object is replaced.

```js
// Make a user
const userReference = await db.collection('users').add({
  address: {
    home: 'San Francisco',
    work: 'Silicon Valley',
  },
  age: 15,
});

// Update user's home-address
await userReference.set({
  address: {
    home: 'Silicon Valley'
  }
}, { merge: true });
```

I would expect this to update the home-address, but leave the work address alone. In Firestore, this is what happens:

```js
const user = await userReference.get();

user.data();
// => { address: { home: 'Silicon Valley', work: 'Silicon Valley' }, age: 15 }
```

In this mock library, instead the entire object is replaced:

```js
const user = await userReference.get();

user.data();
// => { address: { home: 'Silicon Valley' }, age: 15 }
```

**Comment by mikkopaderes** [comment]
Can you show me a codepen or something like that? I've tried this before and Firestore does overwrite the whole object when using `set` even with `merge: true`

**Comment by kimroen** [comment]
@mikkopaderes I was trying to write a test for something that is already in production so I hope that's how it works, but I'll double-check and get back to you for sure!

**Comment by kimroen** [comment]
@mikkopaderes Here's one demonstrating this. Every time you refresh the embedded browser, a user is created with an address object with two fields, then the nested property is updated with `set` and `merge: true`, and the result is printed.

https://codesandbox.io/s/zr52r2vz9m

**Comment by kimroen** [comment]
For `update` however, I was wrong. `update` will overwrite the nested object, unless you use the dot-notation (`address.home`). A fork showing this: https://codesandbox.io/s/vvykzxzpzl

**Comment by mikkopaderes** [comment]
Tried it myself too right now for Firebase JS SDK and the behavior is the same with yours. I might've switched things by accident. I'll find a time to fix this. 😛 

Thanks @kimroen

**Comment by kimroen** [comment]
> Tried it myself too right now for Firebase JS SDK and the behavior is the same with yours. I might've switched things by accident. I'll find a time to fix this. 😛

Nice! I wrote some tests before I started fixing it myself, but I won't have time to look at it any more today, unfortunately.

Feel free to take my branch if you'd like to work on it!

**Comment by mikkopaderes** [comment]
I've looked at my unit tests and I think there's some confusion. It seems that the library already functions the same as Firestore in that `set` with `merge: true` will only updated the appropriate object properties while in `update`, it will overwrite everything.

I might've worded things wrong on the PR the implemented nested updates.

See [here](https://github.com/mikkopaderes/mock-cloud-firestore/blob/6bbd455eb62a546df7fb064cda695dca18c9116e/src/unit-test.js#L593) and [here](https://github.com/mikkopaderes/mock-cloud-firestore/blob/6bbd455eb62a546df7fb064cda695dca18c9116e/src/unit-test.js#L661).

**Comment by kimroen** [comment]
@mikkopaderes I appreciate it! I wrote about some progress on this over in this PR: https://github.com/mikkopaderes/mock-cloud-firestore/pull/74
