### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by wovalle** [mikkopaderes/mock-cloud-firestore#80]
Hey, first of all nice work with this library!

I did a [naive implementation](https://github.com/wovalle/fireorm/blob/master/test/monkey-patch-firestore-transaction.ts) to support transactions and I'm monkey patching your library in my project. It doesn't have any special checks/corner cases, just exposes a compatible api for firestore transactions.

Would you be interested on a PR adding this transactions naive implementation to the library?

Thanks!

**Comment by mikkopaderes** [comment]
Thank you, I would appreciate that. 😃
