### ISSUE TITLE
Saving data as firestore.Timestamp does not return correct type

### ISSUE THREAD

**Issue by mellet** [mikkopaderes/mock-cloud-firestore#88]
```
mockFirestore.collection("something")
  .doc("test")
  .set({
    time: firebase.firestore.Timestamp(new Date())
  })
```

When fetching this through the mock time looks like this:
`createdAt: { _seconds: 1575489056, _nanoseconds: 597000000 }`

In real firebase you can call `toDate()` on the Timestamp to convert it to a normal JS Date object.
But in the mock implementation `toDate()` is not present on the returned value from firebase.

**Comment by mikkopaderes** [comment]
That API isn't supported. I'm also not sure what are the use-case for it right now. What is supported is `firebase.firestore.FieldValue.serverTimestamp()`, maybe that's what you want?

**Comment by mellet** [comment]
As I have understood it the best practice in [firestore](https://firebase.google.com/docs/firestore/manage-data/add-data#data_types) is to store dates as `firstore.Timestamp`.
To do that I can use either of these methods:
```
const nodeJSCreationDate = firebase.firestore.Timestamp(new Date())
const firestoreServerCreationDate = firebase.firestore.FieldValue.serverTimestamp()
```

But when I fetch the data from firebase it has the type of `FirebaseFirestore.Timestamp`.
In firebase this type has the functions:
`isEqual`, `toDate` and `toMillis`
and fields `nanoseconds`, `seconds`

So when I fetch my data from firebase I want to convert it back to a normal Javascript Date object by calling toDate on the Timestamp that firebase gives me.

[Here](https://codeday.me/en/qa/20190305/1949.html) is a post i read about it.

My usecase is that I have two types, one the application uses and one for storing in firebase as shown below. And I want to convert between them when fetching / saving data in firestore.

```typescript
// Application model
type User = {
  name: string;
  createdAt: Date; // Javascript date object
}

// Firestore document model
type UserDoc = {
  name: string;
  createdAt: FirebaseFirestore.Timestamp;
}

function convertToApplicationModel(userDoc: UserDoc): User {
  return {
     ...userDoc,
     // mock-cloud-firestore error, toDate not defined
    createdAt: userDoc.createdAt.toDate()
  }
}

function convertToFirestoreModel(user: User): UserDoc {
  return {
     ...user,
     createdAt: firebase.firestore.Timestamp.fromDate(user.createdAt)
  }
}
```

**Comment by mikkopaderes** [comment]
Actually `toDate` is supported, how are you using it in your code?

**Comment by mellet** [comment]
Failing test:

```javascript
import MockFirebase from "mock-cloud-firestore";
import { Timestamp } from "@google-cloud/firestore";

describe("", () => {
  it("", async () => {
    const firebase = new MockFirebase();
    const firestore = firebase.firestore();

    const testDate = new Date();

    const testUser = {
      nickname: "Hello",
      createdAt: Timestamp.fromDate(testDate)
    };

    // Store user in mock db
    await firestore
      .collection("test")
      .doc("testDoc")
      .set(testUser);

    // Get user
    const documentSnap = await firestore
      .collection("test")
      .doc("testDoc")
      .get();

    const document = documentSnap.data();

    const testConvertTimestamp = document.createdAt.toDate();

    expect(testConvertTimestamp).toEqual(testDate);
  });
});
```

Error:
```
TypeError: document.createdAt.toDate is not a function
```

Console logging the `document`:
```javascript
{
  nickname: 'Hello',
  createdAt: { _seconds: 1575556647, _nanoseconds: 484000000 }
}
```

**Comment by mikkopaderes** [comment]
Yeah so this is because the library doesn't serialize `Timestamp` type. You're better of using `firebase.firestore.FieldValue.serverTimestamp()` for now.

**Comment by mellet** [comment]
I'll give it a shot and see if that works fine for my usecase ;)

**Comment by mikkopaderes** [comment]
Yes please do because if you're only trying to set the current time then that's the recommended way. That method will use the server time so you'll be sure that it's consistent as your current way will depend on the current time of the device (which may vary and probably isn't what you want).

**Comment by mikkopaderes** [comment]
Closing, feel free to reopen if necessary.
