### ISSUE TITLE
Support for offset (skip) and select (projection)

### ISSUE THREAD

**Issue by Cherviakov** [mikkopaderes/mock-cloud-firestore#98]
Would be nice to have support of those options, as if they used cannot make tests using this library.

**Comment by mikkopaderes** [comment]
Can you link the API docs for it?

**Comment by Cherviakov** [comment]
https://googleapis.dev/nodejs/firestore/latest/CollectionReference.html#offset
https://googleapis.dev/nodejs/firestore/latest/CollectionReference.html#select

**Comment by mikkopaderes** [comment]
These are APIs for the Admin SDK of Firestore. This project only aims to support the Firestore for clients.

I would recommend that you use the [Firestore Emulator](https://firebase.google.com/docs/firestore/security/test-rules-emulator) instead.

**Comment by Cherviakov** [comment]
I see, thanks.
